[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --prefix /app/packages/frontend"]

[phases.build]
cmds = ["cd /app/packages/frontend && npx next build"]

[start]
cmd = "cd /app/packages/frontend && npx next start -H 0.0.0.0 -p ${PORT:-3000}"
