[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --ignore-scripts"]

[phases.build]
cmds = ["npx tsc"]

[start]
cmd = "npx knex migrate:latest --knexfile knexfile.js --env production 2>&1 || true; node dist/index.js"
