[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --prefix /app/packages/backend"]

[phases.build]
cmds = ["cd /app/packages/backend && npx tsc"]

[start]
cmd = "cd /app/packages/backend && (npx knex migrate:latest --knexfile knexfile.js --env production 2>&1 || true) && node dist/index.js"
